### ISSUE TITLE
error running notification service

### ISSUE THREAD

**Issue by max397574** [rcarriga/nvim-notify#128] opened 2022-09-03 07:30 UTC
Error running notification service: ...opt/nvim-notify/lua/notify/service/buffer/highlights.lua:118: a
ttempt to call method '_get_hl_from_capture' (a nil value)

**Comment by folke** [comment] 2022-09-03 13:56
Any chance you're using Tokyonight? I merged some PR's yesterday and one of them caused this issue for me. Fixed my issue already on Tokyonight.

The cause for me was `TelescopeNormal` having `None` as bg.

**Comment by rcarriga** [comment] 2022-09-03 16:43
It's due to a breaking change in nightly, should be working now :smile:

**Closed** 2022-09-03 19:13 UTC
