### ISSUE TITLE
Incompatible with multigrid since last commit

### ISSUE THREAD

**Issue by tobealive** [rcarriga/nvim-notify#93] opened 2022-05-03 17:16 UTC
Notifications do not show correctly when using environments with multigrid like neovide or nvui since the last commit.

**Comment by rcarriga** [comment] 2022-05-03 21:03
Please provide more information as I do not use these tools. Detailed description of an error, screenshots, recordings, steps to reproduce etc

**Comment by tobealive** [comment] 2022-05-03 23:39
Yes, I understand when someone's not using those toys. Usually it's the also my choice to go as raw as possible. But it really makes a beneficial difference for me in eye strain and development experience. Things like following cursor movement when, for example, switching windows etc. is easier... Just many situations where I don't want to miss something that is smoothly rendered anymore.

To describe the problem: A Notification usually remains invisible since the last commit, independent of what's triggering it.  For the example of the following video, notify gets triggered by font scaling. I'm using a small lua plugin I wrote(`size-matters` maybe this can serve as a tool for debugging idk). The notifications are just briefly visible when scaling down.

https://user-images.githubusercontent.com/34311583/166590939-f56c1762-8efb-444d-a8a6-cc011f9191cb.mp4

Here is the quick video.You see switching to the current main branch of notify then starting with an app with multigrid enabled. Notifications do not appear when triggered without scaling or scaling up. But when scaling down while triggering a notification, you see that notifications indeed are there, but they seem to live outside the viewport and very briefly. Then starting without multigrid and it's working fine. Then going back to the penultimate commit, and it also works fine with multigrid enabled.
It's hard giving more details as I don't know how to debug this. If you have the time maybe you can do tests or tell me what I can do here to provide you better information.

(I hope I don't confuse anyone with the scaling thing, because this is not a scaling issue. Just when not coincidentally scaling the down simultaneously with a Notification event they remain completely invisible.)

**Comment by rcarriga** [comment] 2022-05-04 06:35
That's perfect thank you, this should be fixed in the latest commit. The cause was using the wrong anchor for the floating value, which didn't appear in regular terminal neovim because it limits the bounds to the screen whereas it seems Neovide allows for moving windows off screen

**Comment by tobealive** [comment] 2022-05-04 11:08
Perfect, thanks alot!

**Closed** 2022-05-05 07:46 UTC
