### ISSUE TITLE
blank notif on nightly

### ISSUE THREAD

**Issue by yofriadi** [rcarriga/nvim-notify#258] opened 2024-02-14 11:52 UTC
<img width="1800" alt="Screenshot 2024-02-14 at 18 45 59" src="https://github.com/rcarriga/nvim-notify/assets/24536844/2b9ff3d6-10c4-4b0c-af54-bb5cc9a8ed91">

as you can see there, the word lazyvim is covered by some notification.

additional info:
- I am using macOS 14.2 Sonoma specifically
- I currently use commit `70a0049` or before 8 feb. where the notif not blank.
- I believe when using WSL, arch specifically the issue the same, but then I switch to other commit that not make notify blank, then revert to latest commit, the issue disappear.

**Comment by lpnh** [comment] 2024-02-14 12:04
I don't know if it's related, but I'm using this fork on my nightly: https://github.com/rcarriga/nvim-notify/pull/253#issuecomment-1937859567

**Comment by yofriadi** [comment] 2024-02-14 13:46
well, I also got that, but only when I first intalling new plugin and thinking it is my setup that made that error, will check that out, thank you!

**Comment by bjornevik** [comment] 2024-02-14 14:12
The reason it happened for me seems to be because I hadn't updated my config after severity_limit deprecation in nvim lsp.

I see in my `NoiceHistory` I get a couple of errors related to nvim-notify, as well as two other ones not related directly to this plugin:

```
15:06:01 msg_show Error running notification service: ...l/share/nvim/lazy/nvim-notify/lua/notify/stages/util.lua:150: attempt to index a number value
15:06:01 msg_show Error running notification service: ...l/share/nvim/lazy/nvim-notify/lua/notify/stages/util.lua:150: attempt to index a number value
```

When I fixed the other errors in my `NoiceHistory` it seems to have fixed this problem, I don't really have time to troubleshoot further, but hope it helps.

**Comment by rcarriga** [comment] 2024-02-14 22:58
Closing as duplicate of #252

**Closed by rcarriga** 2024-02-14 22:58 UTC
