### ISSUE TITLE
How to show lsp server is started like in the readme

### ISSUE THREAD

**Issue by bryant-the-coder** [rcarriga/nvim-notify#66] opened 2022-03-13 07:16 UTC
The title says it all. I followed the code in the readme. There is a very long error

**Comment by rcarriga** [comment] 2022-03-13 08:51
Can you show the error you're getting?

**Comment by bryant-the-coder** [comment] 2022-03-13 11:19
ah wait. can u tell where should i be putting that func in? and will it appear everytime i enter a new file? like i am in init.lua, it pop up for the first time. when i enter mappings.lua, it appears again. will that happen?

**Comment by vogelsgesang** [comment] 2022-03-14 20:10
The code on the wiki makes the implicit assumption that you replaced `vim.notify` by the notification function provided by this plugin. I.e., it assumes that you also have the line

```
vim.notify = require("notify")
```

in your `init.lua`

That's probably something worth changing in the wiki...

**Comment by bryant-the-coder** [comment] 2022-03-15 07:31
@rcarriga

**Comment by rcarriga** [comment] 2022-03-15 07:45
@vogelsgesang Thank you yes this is the problem here, I've updated the wiki to note the assumption.

@bryant-the-coder Please don't tag people unnecessarily, they will see the notifications already and it just acts as spam

Closing this as the problem is solved

**Closed by rcarriga** 2022-03-15 07:45 UTC
