### ISSUE TITLE
How to override the builtin notifications

### ISSUE THREAD

**Issue by Corgile** [rcarriga/nvim-notify#192] opened 2023-04-19 02:24 UTC
Overriding/customizing notification is indeed needed in since sometimes the messages can be so long that cover contents for a long time.

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/48396880/232948885-2f8a573f-57ea-4f26-827e-844cd8ffa04a.png">

my onsave  action is implemented by :

```lua
keycap('n', '<C-S>', '<CMD>lua vim.api.notify(\"current file is saved!\")<CR>')

```

**Comment by rcarriga** [comment] 2023-04-19 08:29
Duplicate of https://github.com/rcarriga/nvim-notify/issues/190, see that issue for solutions

**Closed by rcarriga** 2023-04-19 08:29 UTC

**Comment by RAprogramm** [comment] 2023-08-29 00:50
If long message is problem - you can show only filename in notification body.
I use this keybind with [which-key](https://github.com/folke/which-key.nvim).
```lua
    ['<c-s>'] = {
      function()
        vim.cmd('silent! wa')
        vim.notify(
          'File "' .. vim.fn.expand('%:t') .. '" was saved',
          2,
          { title = 'Saved', icon = '✓' }
        )
      end,
      'Save file ',
    },

```

**Comment by Wangch29** [comment] 2024-10-23 04:53
My approach is 

vim.api.nvim_create_autocmd("BufWritePost", {
  callback = function()
    local file_name = vim.fn.expand('%')
    vim.notify("Saved file: " .. file_name, vim.log.levels.INFO,
      {
        title = "Save Notification",
        timeout = 100,
        icon = ""
      })
  end,
})
