### ISSUE TITLE
Flickering when rendering large notifications

### ISSUE THREAD

**Issue by vogelsgesang** [rcarriga/nvim-notify#56] opened 2022-01-29 13:29 UTC
As can be seen in the following screen recording, the text cursor jumps between the notification body and the opened document repeatedly, leading to some flickering

https://user-images.githubusercontent.com/6820896/151662787-4c5b3369-62fa-4b5a-b5e9-f4586f5ac5fb.mov

(In this case the large notification body comes from `clangd`s "Dump AST" functionality, i.e. a debugging utility which sends a dump of a C++ AST as a notification over the LSP protocol)

**Comment by rcarriga** [comment] 2022-01-31 21:34
I don't seem to be able to reproduce this, does this happen consistently? Can you provide the text which it occurs with? Also does it happen when not inside tmux?

**Comment by vogelsgesang** [comment] 2022-02-01 12:03
> does this happen consistently?

Yes, it does, but only for large notifications.

> Can you provide the text which it occurs with?

The flickering is not associated to any specific text, it seems to occur for all large enough messages.
Interestingly, in the Telescope notification window there is no flickering, also not for larger messages.
This Lua snippet triggers the flickering for me reliably:
```
local text = [[FunctionDecl 0x7fb246a362f8 </home/tsi/avogelsgesang/Documents/llvm-project/clang-tools-extra/clangd/refactor/tweaks/ExpandAutoType.cpp:58:1, line:64:1> line:58:6 used isStructuredBindingType 'bool (const SelectionTree::Node *)'
|-ParmVarDecl 0x7fb246a361f0 <col:30, col:57> col:57 used N 'const SelectionTree::Node *'
|-CompoundStmt 0x7fb246a4f708 <col:60, line:64:1>
| |-WhileStmt 0x7fb246a4eeb8 <line:60:3, line:61:12>
| | |-BinaryOperator 0x7fb246a4ed28 <line:60:10, col:39> 'bool' '&&'
| | | |-ImplicitCastExpr 0x7fb246a4ecf8 <col:10> 'bool' <PointerToBoolean>
| | | | `-ImplicitCastExpr 0x7fb246a4ece0 <col:10> 'const SelectionTree::Node *' <LValueToRValue>
| | | |   `-DeclRefExpr 0x7fb246a363e8 <col:10> 'const SelectionTree::Node *' lvalue ParmVar 0x7fb246a361f0 'N' 'const SelectionTree::Node *'
| | | `-ImplicitCastExpr 0x7fb246a4ed10 <col:15, col:39> 'bool' <PointerToBoolean>
| | |   `-CXXMemberCallExpr 0x7fb246a36d50 <col:15, col:39> 'const clang::TypeLoc *'
| | |     `-MemberExpr 0x7fb246a36cc0 <col:15, col:37> '<bound member function type>' .get 0x7fb246a36bc8
| | |       `-MemberExpr 0x7fb246a36698 <col:15, col:18> 'const clang::DynTypedNode' lvalue ->ASTNode 0x7fb246a36448
| | |         `-ImplicitCastExpr 0x7fb246a36428 <col:15> 'const SelectionTree::Node *' <LValueToRValue>
| | |           `-DeclRefExpr 0x7fb246a36408 <col:15> 'const SelectionTree::Node *' lvalue ParmVar 0x7fb246a361f0 'N' 'const SelectionTree::Node *'
| | `-BinaryOperator 0x7fb246a4ee68 <line:61:5, col:12> 'const SelectionTree::Node *' lvalue '='
| |   |-DeclRefExpr 0x7fb246a4ed48 <col:5> 'const SelectionTree::Node *' lvalue ParmVar 0x7fb246a361f0 'N' 'const SelectionTree::Node *'
| |   `-ImplicitCastExpr 0x7fb246a4ee50 <col:9, col:12> 'const SelectionTree::Node *' <NoOp>
| |     `-ImplicitCastExpr 0x7fb246a4ee38 <col:9, col:12> 'clang::clangd::SelectionTree::Node *' <LValueToRValue>
| |       `-MemberExpr 0x7fb246a4ee08 <col:9, col:12> 'clang::clangd::SelectionTree::Node *const' lvalue ->Parent 0x7fb246a4eda8
| |         `-ImplicitCastExpr 0x7fb246a4ed88 <col:9> 'const SelectionTree::Node *' <LValueToRValue>
| |           `-DeclRefExpr 0x7fb246a4ed68 <col:9> 'const SelectionTree::Node *' lvalue ParmVar 0x7fb246a361f0 'N' 'const SelectionTree::Node *'
| `-ReturnStmt 0x7fb246a4f6c8 <line:63:3, col:49>
|   `-BinaryOperator 0x7fb246a4f6a8 <col:10, col:49> 'bool' '&&'
|     |-ImplicitCastExpr 0x7fb246a4f678 <col:10> 'bool' <PointerToBoolean>
|     | `-ImplicitCastExpr 0x7fb246a4f660 <col:10> 'const SelectionTree::Node *' <LValueToRValue>
|     |   `-DeclRefExpr 0x7fb246a4eed8 <col:10> 'const SelectionTree::Node *' lvalue ParmVar 0x7fb246a361f0 'N' 'const SelectionTree::Node *'
|     `-ImplicitCastExpr 0x7fb246a4f690 <col:15, col:49> 'bool' <PointerToBoolean>
|       `-CXXMemberCallExpr 0x7fb246a4f640 <col:15, col:49> 'const clang::DecompositionDecl *'
|         `-MemberExpr 0x7fb246a4f5b0 <col:15, col:47> '<bound member function type>' .get 0x7fb246a4f4b8
|           `-MemberExpr 0x7fb246a4ef30 <col:15, col:18> 'const clang::DynTypedNode' lvalue ->ASTNode 0x7fb246a36448
|             `-ImplicitCastExpr 0x7fb246a4ef18 <col:15> 'const SelectionTree::Node *' <LValueToRValue>
|               `-DeclRefExpr 0x7fb246a4eef8 <col:15> 'const SelectionTree::Node *' lvalue ParmVar 0x7fb246a361f0 'N' 'const SelectionTree::Node *'
`-FullComment 0x7fb247058090 <line:56:3, line:57:79>
  `-ParagraphComment 0x7fb247058060 <line:56:3, line:57:79>
    |-TextComment 0x7fb247057fc0 <line:56:3, col:54> Text=" Structured bindings must use auto, e.g. `const auto"
    |-TextComment 0x7fb247057fe0 <col:55> Text="&"
    |-TextComment 0x7fb247058000 <col:56, col:72> Text=" [a,b,c] = ...;`."
    `-TextComment 0x7fb247058020 <line:57:3, col:79> Text=" Return whether N (an AutoTypeLoc) is such an auto that must not be expanded."
]]

require("notify")(text)
```

> does it happen when not inside tmux?

Yes, this also happens outside of tmux.
But now that I think about it: I am using nvim over a ssh connection with a rather bad latency/bandwidth.

> I don't seem to be able to reproduce this

Don't worry too much.
With #57, I no longer see a need for such large notifications, anyway.

**Comment by rcarriga** [comment] 2022-02-07 19:14
I'm going to close this as it's likely due to a slow connection, which we can't do much about and there's a suitable workaround.

**Closed by rcarriga** 2022-02-07 19:14 UTC
Labels: bug, wontfix

**Comment by tami5** [comment] 2022-02-24 13:22
I'm facing similar issue, cursor blinking so badly when ever there is a notification, it became like a bad indication of new notification running.

**Comment by rodhash** [comment] 2022-09-14 08:02
having somewhat similar issue, in my case it's more when the notification is sliding out .. this "movement" sometimes is kind lagging ..

Tried increasing FPS and frequency, they seem to help but doesn't fix .. sometimes I keep getting that lagging movement

**Comment by rodhash** [comment] 2022-09-21 02:56
Thanks .. Non transparent BG seems to help quite a bit, that lag seems to happen way less often
