### ISSUE TITLE
/stages/util.lua:150: attempt to index a number value

### ISSUE THREAD

**Issue by qRoC** [rcarriga/nvim-notify#257] opened 2024-02-12 16:44 UTC
This fixed if all `[false]` are removed

**Comment by dpetka2001** [comment] 2024-02-12 20:33
Duplicate of #252 and there's already a [PR](https://github.com/rcarriga/nvim-notify/pull/253) for fixing it.

**Comment by rcarriga** [comment] 2024-02-14 22:57
Closing as duplicate

**Closed by rcarriga** 2024-02-14 22:57 UTC
